stages:
  - build
  - release

variables:
  ENV_NAME: arduino_nano_esp32
  BIN_PATH: .pio/build/$ENV_NAME/firmware.bin

build-firmware:
  stage: build
  image: python:3.11
  script:
    - pip install platformio
    - pio run -e $ENV_NAME --disable-auto-clean
  artifacts:
    paths:
      - $BIN_PATH
    expire_in: 1 hour
  rules:
    - if: $CI_COMMIT_TAG =~ /^v.*/

release-firmware:
  stage: release
  image: alpine:latest
  needs: [build-firmware]
  script:
    - apk add --no-cache curl jq coreutils
    - SHA=$(sha256sum $BIN_PATH | awk '{print $1}')
    - BINARY=$(base64 -w 0 $BIN_PATH)
    - |
      curl -X POST "https://mellin.net/wellaware/api/v1/ota/release" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $OTA_ADMIN_SECRET" \
        -d "{
          \"version\": \"$CI_COMMIT_TAG\",
          \"sha256\": \"$SHA\",
          \"binary\": \"$BINARY\"
        }"
  rules:
    - if: $CI_COMMIT_TAG =~ /^v.*/